language: objective-c
osx_image: xcode10
xcode_project: Bradel.xcodeproj
xcode_scheme: Bradel
xcode_sdk: iphoneos12.0
env:
  global:
  - FRAMEWORK_NAME=Bradel
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
script: xcodebuild clean && xcodebuild build -project Bradel.xcodeproj -scheme Bradel
before_deploy:
- carthage build --no-skip-current
- carthage archive $FRAMEWORK_NAME
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_API_KEY
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: adhumi/Bradel
    tags: true
